# combined.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student_war-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student_war-deployment
  template:
    metadata:
      labels:
        app: student_war-deployment
    spec:
      containers:
      - name: student_war-deployment
        image: ajaymadane/studentapplication:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student_war-service
spec:
  selector:
    app: student_war-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
